'use strict';

// Registry of known AI tools — matched by app name or developer name (case-insensitive)
const AI_TOOLS = [
  {
    canonical_name: 'ChatGPT',
    namePatterns: ['chatgpt', 'openai'],
    developerPatterns: ['openai'],
    category: 'Generative AI',
    data_training_clause: true,
    data_retention: '30 days (API)',
    server_geography: 'US',
    trains_on_data: false, // enterprise opt-out exists; consumer: true
    notes: 'Enterprise plans exclude training. Consumer free tier may use conversations for training.',
  },
  {
    canonical_name: 'Claude (Anthropic)',
    namePatterns: ['claude'],
    developerPatterns: ['anthropic'],
    category: 'Generative AI',
    data_training_clause: false,
    data_retention: '30 days',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Anthropic does not train on API or Claude.ai Pro/Team conversations.',
  },
  {
    canonical_name: 'Gemini',
    namePatterns: ['gemini', 'google ai', 'bard'],
    developerPatterns: ['google llc', 'google workspace'],
    category: 'Generative AI',
    data_training_clause: true,
    data_retention: 'Varies by product',
    server_geography: 'Global',
    trains_on_data: true,
    notes: 'Workspace Admin can disable Gemini data usage. Consumer Gemini may train.',
  },
  {
    canonical_name: 'Microsoft Copilot',
    namePatterns: ['copilot', 'm365 chat', 'bing chat'],
    developerPatterns: [],
    category: 'Generative AI',
    data_training_clause: false,
    data_retention: '30 days',
    server_geography: 'US / EU',
    trains_on_data: false,
    notes: 'M365 Copilot bound by Microsoft data processing agreement. Does not train on tenant data.',
  },
  {
    canonical_name: 'Perplexity',
    namePatterns: ['perplexity'],
    developerPatterns: ['perplexity'],
    category: 'AI Search',
    data_training_clause: true,
    data_retention: 'Unknown',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'Perplexity uses conversations to improve models. No enterprise DPA widely available.',
  },
  {
    canonical_name: 'Grammarly',
    namePatterns: ['grammarly'],
    developerPatterns: ['grammarly'],
    category: 'AI Writing',
    data_training_clause: true,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'Text submitted is used to improve Grammarly AI. Enterprise plan has data deletion controls.',
  },
  {
    canonical_name: 'Notion AI',
    namePatterns: ['notion'],
    developerPatterns: ['notion'],
    category: 'AI Productivity',
    data_training_clause: false,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Notion AI uses third-party LLMs. User content not used for training per ToS.',
  },
  {
    canonical_name: 'Otter.ai',
    namePatterns: ['otter.ai', 'otter ai', 'otterai', 'otter'],
    developerPatterns: ['aisense', 'otter'],
    category: 'AI Transcription',
    data_training_clause: true,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'Meeting transcriptions stored and may be used to improve AI. Highly sensitive for M&A or legal discussions.',
  },
  {
    canonical_name: 'Jasper',
    namePatterns: ['jasper'],
    developerPatterns: ['jasper'],
    category: 'AI Writing',
    data_training_clause: false,
    data_retention: '30 days',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Jasper Business/Enterprise does not train on customer content.',
  },
  {
    canonical_name: 'Copy.ai',
    namePatterns: ['copy.ai', 'copyai'],
    developerPatterns: ['copy.ai'],
    category: 'AI Writing',
    data_training_clause: true,
    data_retention: 'Unknown',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'ToS allows improving services using input/output data.',
  },
  {
    canonical_name: 'GitHub Copilot',
    namePatterns: ['github copilot', 'github'],
    developerPatterns: ['github'],
    category: 'AI Coding',
    data_training_clause: false,
    data_retention: 'Ephemeral (API)',
    server_geography: 'US / EU',
    trains_on_data: false,
    notes: 'GitHub does not train Copilot on Business/Enterprise code. Individual plan may contribute to training.',
  },
  {
    canonical_name: 'Zapier',
    namePatterns: ['zapier'],
    developerPatterns: ['zapier'],
    category: 'AI Automation',
    data_training_clause: false,
    data_retention: 'Varies by plan',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Zapier AI features may process sensitive data across connected apps.',
  },
  {
    canonical_name: 'Make (Integromat)',
    namePatterns: ['make', 'integromat'],
    developerPatterns: ['celonis', 'make.com'],
    category: 'AI Automation',
    data_training_clause: false,
    data_retention: '30 days',
    server_geography: 'EU',
    trains_on_data: false,
    notes: 'GDPR-compliant EU-based automation. Data stays in EU by default.',
  },
  {
    canonical_name: 'Glean',
    namePatterns: ['glean'],
    developerPatterns: ['glean'],
    category: 'AI Search',
    data_training_clause: false,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Glean indexes internal data. Tenant data is isolated, not used to train shared models.',
  },
  {
    canonical_name: 'Cohere',
    namePatterns: ['cohere'],
    developerPatterns: ['cohere'],
    category: 'Generative AI',
    data_training_clause: true,
    data_retention: 'Unknown',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Enterprise agreements typically opt out of training. Review your contract.',
  },
  {
    canonical_name: 'Hugging Face',
    namePatterns: ['hugging face', 'huggingface'],
    developerPatterns: ['hugging face'],
    category: 'AI Platform',
    data_training_clause: true,
    data_retention: 'Unknown',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'Public Spaces may expose submitted data. Enterprise tier has data isolation.',
  },
  {
    canonical_name: 'Midjourney',
    namePatterns: ['midjourney'],
    developerPatterns: ['midjourney'],
    category: 'AI Image',
    data_training_clause: true,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'All prompts and outputs may be used for training. Sensitive prompts could be publicly visible on free plan.',
  },
  {
    canonical_name: 'Writesonic',
    namePatterns: ['writesonic'],
    developerPatterns: ['writesonic'],
    category: 'AI Writing',
    data_training_clause: true,
    data_retention: 'Unknown',
    server_geography: 'US',
    trains_on_data: true,
    notes: 'Business plan may use content to improve AI. Review data processing agreement.',
  },
  {
    canonical_name: 'Fireflies.ai',
    namePatterns: ['fireflies', 'fireflies.ai'],
    developerPatterns: ['fireflies'],
    category: 'AI Transcription',
    data_training_clause: true,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Meeting recordings stored and transcribed. High-sensitivity for confidential business calls.',
  },
  {
    canonical_name: 'Gong',
    namePatterns: ['gong'],
    developerPatterns: ['gong.io', 'gong'],
    category: 'AI Sales',
    data_training_clause: false,
    data_retention: 'Account lifetime',
    server_geography: 'US',
    trains_on_data: false,
    notes: 'Records and analyzes sales calls. High-sensitivity — customer data and deal info exposed.',
  },
];

function detectAITool(appName, developerName) {
  const nameLower = (appName || '').toLowerCase();
  const devLower = (developerName || '').toLowerCase();

  for (const tool of AI_TOOLS) {
    if (tool.namePatterns.some(p => nameLower.includes(p))) return tool;
    if (devLower && tool.developerPatterns.some(p => devLower.includes(p))) return tool;
  }
  return null;
}

module.exports = { AI_TOOLS, detectAITool };
