'use strict';

// Static pricing registry for common SaaS tools.
// it_plan_price_per_user: $ per user per month (null if flat-rate)
// it_plan_price_flat: $ per month flat (null if per-user)
// When both null: pricing is custom/contact-sales

const PRICING = [
  {
    namePatterns: ['chatgpt', 'openai'],
    developerPatterns: ['openai'],
    app_name: 'ChatGPT',
    category: 'AI / LLM',
    has_free_tier: true,
    it_plan_name: 'Team',
    it_plan_price_per_user: 25,
    it_plan_price_flat: null,
    it_plan_notes: 'Admin console, usage analytics, no training on your data',
  },
  {
    namePatterns: ['claude', 'anthropic'],
    developerPatterns: ['anthropic'],
    app_name: 'Claude',
    category: 'AI / LLM',
    has_free_tier: true,
    it_plan_name: 'Team',
    it_plan_price_per_user: 25,
    it_plan_price_flat: null,
    it_plan_notes: 'Team workspace, admin controls, no training on your data',
  },
  {
    namePatterns: ['gemini', 'google ai', 'google workspace ai'],
    developerPatterns: ['google'],
    app_name: 'Gemini for Workspace',
    category: 'AI / LLM',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 20,
    it_plan_price_flat: null,
    it_plan_notes: 'Integrated into Google Workspace, admin policies',
  },
  {
    namePatterns: ['copilot', 'github copilot'],
    developerPatterns: ['github', 'microsoft'],
    app_name: 'GitHub Copilot',
    category: 'AI / Developer',
    has_free_tier: false,
    it_plan_name: 'Business',
    it_plan_price_per_user: 19,
    it_plan_price_flat: null,
    it_plan_notes: 'Policy management, IP indemnity, audit logs',
  },
  {
    namePatterns: ['perplexity'],
    developerPatterns: ['perplexity'],
    app_name: 'Perplexity',
    category: 'AI / Search',
    has_free_tier: true,
    it_plan_name: 'Enterprise Pro',
    it_plan_price_per_user: 40,
    it_plan_price_flat: null,
    it_plan_notes: 'SSO, admin controls, no data used for training',
  },
  {
    namePatterns: ['grammarly'],
    developerPatterns: ['grammarly'],
    app_name: 'Grammarly',
    category: 'Productivity',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 15,
    it_plan_price_flat: null,
    it_plan_notes: 'Admin dashboard, style guide, centralized billing',
  },
  {
    namePatterns: ['notion'],
    developerPatterns: ['notion'],
    app_name: 'Notion',
    category: 'Productivity',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 15,
    it_plan_price_flat: null,
    it_plan_notes: 'SAML SSO, advanced permissions, audit logs',
  },
  {
    namePatterns: ['otter.ai', 'otter ai'],
    developerPatterns: ['aisense'],
    app_name: 'Otter.ai',
    category: 'AI / Meetings',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 20,
    it_plan_price_flat: null,
    it_plan_notes: 'Admin console, usage reporting, SSO',
  },
  {
    namePatterns: ['fireflies', 'fireflies.ai'],
    developerPatterns: ['fireflies'],
    app_name: 'Fireflies.ai',
    category: 'AI / Meetings',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 19,
    it_plan_price_flat: null,
    it_plan_notes: 'Admin controls, unlimited transcription, integrations',
  },
  {
    namePatterns: ['salesforce'],
    developerPatterns: ['salesforce'],
    app_name: 'Salesforce',
    category: 'CRM',
    has_free_tier: false,
    it_plan_name: 'Professional',
    it_plan_price_per_user: 80,
    it_plan_price_flat: null,
    it_plan_notes: 'Full CRM, opportunity management, reports',
  },
  {
    namePatterns: ['hubspot'],
    developerPatterns: ['hubspot'],
    app_name: 'HubSpot',
    category: 'CRM / Marketing',
    has_free_tier: true,
    it_plan_name: 'Starter',
    it_plan_price_per_user: null,
    it_plan_price_flat: 50,
    it_plan_notes: 'Starts at $50/mo. Removes HubSpot branding, additional features',
  },
  {
    namePatterns: ['zapier'],
    developerPatterns: ['zapier'],
    app_name: 'Zapier',
    category: 'Automation',
    has_free_tier: true,
    it_plan_name: 'Team',
    it_plan_price_per_user: null,
    it_plan_price_flat: 69,
    it_plan_notes: 'Shared workspace, unlimited users, advanced features',
  },
  {
    namePatterns: ['docusign'],
    developerPatterns: ['docusign'],
    app_name: 'DocuSign',
    category: 'e-Signature',
    has_free_tier: false,
    it_plan_name: 'Standard',
    it_plan_price_per_user: 25,
    it_plan_price_flat: null,
    it_plan_notes: 'Shared templates, team management, reporting',
  },
  {
    namePatterns: ['workday'],
    developerPatterns: ['workday'],
    app_name: 'Workday',
    category: 'HR / ERP',
    has_free_tier: false,
    it_plan_name: 'Enterprise',
    it_plan_price_per_user: null,
    it_plan_price_flat: null,
    it_plan_notes: 'Custom enterprise pricing — contact sales',
  },
  {
    namePatterns: ['bamboohr', 'bamboo hr'],
    developerPatterns: ['bamboohr'],
    app_name: 'BambooHR',
    category: 'HR',
    has_free_tier: false,
    it_plan_name: 'Advantage',
    it_plan_price_per_user: 8,
    it_plan_price_flat: null,
    it_plan_notes: 'Approx $8/user/mo. Includes reporting, onboarding, e-signatures',
  },
  {
    namePatterns: ['slack'],
    developerPatterns: ['slack'],
    app_name: 'Slack',
    category: 'Communication',
    has_free_tier: true,
    it_plan_name: 'Pro',
    it_plan_price_per_user: 7.25,
    it_plan_price_flat: null,
    it_plan_notes: 'Full message history, unlimited integrations',
  },
  {
    namePatterns: ['zoom'],
    developerPatterns: ['zoom'],
    app_name: 'Zoom',
    category: 'Video / Meetings',
    has_free_tier: true,
    it_plan_name: 'Pro',
    it_plan_price_per_user: 14.99,
    it_plan_price_flat: null,
    it_plan_notes: 'No 40-min limit, cloud recording, admin portal',
  },
  {
    namePatterns: ['dropbox'],
    developerPatterns: ['dropbox'],
    app_name: 'Dropbox',
    category: 'Cloud Storage',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 15,
    it_plan_price_flat: null,
    it_plan_notes: 'Admin console, team folders, SSO',
  },
  {
    namePatterns: ['figma'],
    developerPatterns: ['figma'],
    app_name: 'Figma',
    category: 'Design',
    has_free_tier: true,
    it_plan_name: 'Organization',
    it_plan_price_per_user: 45,
    it_plan_price_flat: null,
    it_plan_notes: 'Centralized admin, SSO, shared libraries',
  },
  {
    namePatterns: ['airtable'],
    developerPatterns: ['airtable'],
    app_name: 'Airtable',
    category: 'Database / Productivity',
    has_free_tier: true,
    it_plan_name: 'Team',
    it_plan_price_per_user: 20,
    it_plan_price_flat: null,
    it_plan_notes: 'Team collaboration, automations, admin controls',
  },
  {
    namePatterns: ['monday'],
    developerPatterns: ['monday'],
    app_name: 'Monday.com',
    category: 'Project Management',
    has_free_tier: true,
    it_plan_name: 'Pro',
    it_plan_price_per_user: 16,
    it_plan_price_flat: null,
    it_plan_notes: 'Time tracking, automations, chart view',
  },
  {
    namePatterns: ['asana'],
    developerPatterns: ['asana'],
    app_name: 'Asana',
    category: 'Project Management',
    has_free_tier: true,
    it_plan_name: 'Starter',
    it_plan_price_per_user: 10.99,
    it_plan_price_flat: null,
    it_plan_notes: 'Timeline, dashboards, custom fields',
  },
  {
    namePatterns: ['loom'],
    developerPatterns: ['loom'],
    app_name: 'Loom',
    category: 'Video Messaging',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 12.5,
    it_plan_price_flat: null,
    it_plan_notes: 'Unlimited recording, custom branding, analytics',
  },
  {
    namePatterns: ['miro'],
    developerPatterns: ['miro'],
    app_name: 'Miro',
    category: 'Collaboration',
    has_free_tier: true,
    it_plan_name: 'Business',
    it_plan_price_per_user: 16,
    it_plan_price_flat: null,
    it_plan_notes: 'Unlimited boards, SSO, advanced admin',
  },
];

function lookupPricing(appName, developerName) {
  const nameLower = (appName || '').toLowerCase();
  const devLower  = (developerName || '').toLowerCase();
  for (const entry of PRICING) {
    if (entry.namePatterns.some(p => nameLower.includes(p))) return entry;
    if (devLower && entry.developerPatterns?.some(p => devLower.includes(p))) return entry;
  }
  return null;
}

function estimateMonthlyCost(entry, userCount) {
  if (!entry) return null;
  if (entry.it_plan_price_per_user != null) {
    return Math.round(entry.it_plan_price_per_user * Math.max(userCount, 1) * 100) / 100;
  }
  if (entry.it_plan_price_flat != null) {
    return entry.it_plan_price_flat;
  }
  return null; // custom pricing
}

module.exports = { lookupPricing, estimateMonthlyCost, PRICING };
